---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tobiajo/microservices-spring
          searchPaths: config
server:
  port: 8001
# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false
