---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: ran,knew,had,saw,bought

server:
  port: ${PORT:${SERVER_PORT:0}}  # this will cause a random, unused port to be assigned if none is specified.
